/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, RequestResult } from "../.kubb/client";
import type { GetApiHealthOptions, GetApiHealthResponses } from "../types";

import { client } from "../.kubb/client";

/**
 * {@link /api/health}
 */
export function getApiHealth<ThrowOnError extends boolean = true>(
  options: Options<GetApiHealthOptions, ThrowOnError> = {}
): Promise<RequestResult<GetApiHealthResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options;

  return request({ method: "GET", url: "/api/health", ...config }) as Promise<
    RequestResult<GetApiHealthResponses, ThrowOnError>
  >;
}
