/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type User = {
  readonly id: string;
  name: string;
  email: string;
  /**
   * @default false
   * @type boolean
   */
  readonly emailVerified: boolean;
  image?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  updatedAt: string;
  readonly role?: string;
  /**
   * @default false
   * @type boolean | undefined
   */
  readonly banned?: boolean;
  readonly banReason?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  readonly banExpires?: string;
};

export type Session = {
  readonly id: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  expiresAt: string;
  token: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  updatedAt: string;
  ipAddress?: string;
  userAgent?: string;
  userId: string;
  readonly impersonatedBy?: string;
  readonly activeOrganizationId?: string;
};

export type Account = {
  readonly id: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken?: string;
  refreshToken?: string;
  idToken?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  accessTokenExpiresAt?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  refreshTokenExpiresAt?: string;
  scope?: string;
  password?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  updatedAt: string;
};

export type Verification = {
  readonly id: string;
  identifier: string;
  value: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  expiresAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  updatedAt: string;
};

export type Organization = {
  readonly id: string;
  name: string;
  slug: string;
  logo?: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  metadata?: string;
};

export type OrganizationRole = {
  readonly id: string;
  organizationId: string;
  role: string;
  permission: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  updatedAt?: string;
};

export type Member = {
  readonly id: string;
  organizationId: string;
  userId: string;
  /**
   * @default 'member'
   * @type string
   */
  role: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
};

export type Invitation = {
  readonly id: string;
  organizationId: string;
  email: string;
  role?: string;
  /**
   * @default 'pending'
   * @type string
   */
  status: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  expiresAt: string;
  /**
   * @description
   * Format: `date-time`
   * @type string
   */
  createdAt: string;
  inviterId: string;
};

export type GetApiHealthStatus200 = {
  status: string;
};

export type GetApiHealthOptions = {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
};

export type GetApiHealthResponses = {
  "200": GetApiHealthStatus200;
};

/**
 * @description Union of all possible responses
 */
export type GetApiHealthResponse = GetApiHealthStatus200;
