/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/client";
import type { GetApiHealthStatus200 } from "../types";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import { getApiHealth } from "../clients/get-api-health";

export const getApiHealthQueryKey = () => [{ url: "/api/health" }] as const;

type GetApiHealthQueryKey = ReturnType<typeof getApiHealthQueryKey>;

export function getApiHealthQueryOptions(
  config: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">> = {}
) {
  const queryKey = getApiHealthQueryKey();
  return queryOptions<
    GetApiHealthStatus200,
    ResponseErrorConfig<Error>,
    GetApiHealthStatus200,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      const { data } = await getApiHealth({
        ...config,
        signal: config.signal ?? signal,
        throwOnError: true,
      });
      return data;
    },
  });
}

/**
 * {@link /api/health}
 */
export function useGetApiHealth<
  TData = GetApiHealthStatus200,
  TQueryData = GetApiHealthStatus200,
  TQueryKey extends QueryKey = GetApiHealthQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiHealthStatus200,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">>;
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getApiHealthQueryKey();

  const queryResult = useQuery(
    {
      ...getApiHealthQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  queryResult.queryKey = queryKey as TQueryKey;

  return queryResult;
}
